# Generated by Django 5.1.6 on 2025-02-13 16:13

import commonutils.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_profile_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=commonutils.util.universal_image_path,
                    ),
                ),
                ("update", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="accounts.profile",
                    ),
                ),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to="accounts.profile"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
