# Generated by Django 5.1.6 on 2025-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="posts.hashtag"
            ),
        ),
    ]
