# Generated by Django 5.1.6 on 2025-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
