# Generated by Django 5.1.6 on 2025-05-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_username"),
        ("posts", "0004_post_is_published_post_publish_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hashtags",
                to="accounts.profile",
            ),
        ),
    ]
