# Generated by Django 5.1.6 on 2025-03-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_friends"),
        ("interactions", "0001_initial"),
        ("posts", "0003_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likeunlikedislike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="likeunlikedislike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_likes",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="likeunlikedislike",
            name="value",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("Unlike", "Unlike"),
                    ("dislike", "Dislike"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="likeunlikedislike",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_post_like"
            ),
        ),
    ]
