# Generated by Django 5.1.6 on 2025-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_alter_likeunlikedislike_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likeunlikedislike",
            name="value",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("Unlike", "Unlike"),
                    ("Dislike", "Dislike"),
                ],
                max_length=8,
            ),
        ),
    ]
