# Generated by Django 5.1.6 on 2025-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_alter_likeunlikedislike_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likeunlikedislike",
            name="value",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")], max_length=8
            ),
        ),
    ]
