# Generated by Django 5.1.6 on 2025-02-10 12:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(default="fill out a bio", max_length=600)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.profile_image_path,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
