# Generated by Django 5.1.6 on 2025-02-08 17:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                default="avatar.png", upload_to=accounts.models.profile_image_path
            ),
        ),
    ]
