# Generated by Django 5.1.6 on 2025-02-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
    ]
