# Generated by Django 5.1.6 on 2025-02-08 18:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.profile_image_path
            ),
        ),
    ]
