# Generated by Django 5.1.6 on 2025-03-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="friends",
        ),
    ]
