# Generated by Django 5.1.6 on 2025-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="username"),
        ),
    ]
